server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          my-oauth2-client:
            client-id: oauth2-demo-client
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/oauth2-demo-client
        provider:
          my-oauth2-client:
            logout-url: http://localhost:8180/realms/oauth2-demo-realm/protocol/openid-connect/logout
            issuer-uri: http://localhost:8180/realms/oauth2-demo-realm
            user-name-attribute: preferred_username
            claims:
              roles: resource_access.oauth2-demo-client.roles #resource_access={oauth2-demo-client={roles=[xxx,yyy]}}

logging:
  level:
    org.springframework.security: DEBUG
